name: Lint Rules Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Git diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --color FETCH_HEAD...

      - name: Install Lint Rules
        run: |
          curl -fsSL https://www.lintrule.com/install.sh | bash

      - name: Run Lint Rules Check
        run: |
          rules check --secret "{{ secrets.LINTRULE_SECRET }}"
